<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USER-20151206XD" name="Default test" tests="5" failures="0" timestamp="22 Mar 2019 14:19:16 GMT" time="0.3" errors="0">
  <testcase name="@BeforeSuite startTest" time="0.0" classname="com.demo.test.testcases.login.LoginPage_op002_loginfail_Test">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.demo.test.base.BaseParpare.startTest(BaseParpare.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite startTest -->
  <testcase name="cxTest" time="0.0" classname="com.demo.test.testcases.search.SearchPage_001_SearchSuccessFunction_Test">
    <skipped/>
  </testcase> <!-- cxTest -->
  <testcase name="loginsuc" time="0.0" classname="com.demo.test.testcases.login.LoginPage_op001_loginsuc_Test">
    <skipped/>
  </testcase> <!-- loginsuc -->
  <testcase name="openurlfail" time="0.0" classname="com.demo.test.testcases.openurl.OpenurlPage_op004_openurlfail_Test">
    <skipped/>
  </testcase> <!-- openurlfail -->
  <testcase name="openurlsucss" time="0.0" classname="com.demo.test.testcases.openurl.OpenurlPage_op003_openurlsucss_Test">
    <skipped/>
  </testcase> <!-- openurlsucss -->
  <testcase name="loginfail" time="0.0" classname="com.demo.test.testcases.login.LoginPage_op002_loginfail_Test">
    <skipped/>
  </testcase> <!-- loginfail -->
</testsuite> <!-- Default test -->
